version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

  pre_build:
    commands:
      - echo "Initializing environment"
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
          --domain luekrit \
          --domain-owner 801681997379 \
          --region ap-southeast-2 \
          --query authorizationToken \
          --output text)

  build:
    commands:
      - echo Build started on `date`
      - mvn clean install -s settings.xml

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Packaging artifacts...
      - mvn package -s settings.xml

artifacts:
  files:
    - target/*.war
  discard-paths: no